### ISSUE TITLE
Downloading issues

### ISSUE THREAD

**Issue by jedikalimero** [Eivy/TwitterImageDownloader#1]
The Add on is not downloading images correctly. When I click Select All, all images are marked with the square but the number above the download button doesn't change. It only changes when I click the images to mark or unmark them individually. In any case, clicking Download does nothing. But sometimes it does. I click on the add on button, mark some images manually  and they get downloaded perfectly but others, nothing is downloaded.

**Comment by Eivy** [comment]
Thanks for reporting issue.
If there were some media that can't download in selected items, all downloads are failed.
So, for now, fix to skip failed media and download else, and mark failed item.
