### ISSUE TITLE
Add on tries to download all images in user's timeline

### ISSUE THREAD

**Issue by jedikalimero** [Eivy/TwitterImageDownloader#2]
The add on finds all images (and videos) in the user's timeline, not only the images posted by the user but also other's retweeted by the user. This can be an inconvenience sometimes. I think you should add some selection filters apart from "Select All". Something like "Select only current user's Images", "Select only images", "Select only videos", etc.

Also, the add on finds only images IN THE TIMELINE but it doesn't find images that the user has uploaded as a response to other tweets (even to their own tweets as in a story)

**Comment by Eivy** [comment]
Your idea sounds good. So, I did it! Let's check v2.1.0!
